### ISSUE TITLE
Quick Start demo error

### ISSUE THREAD

**Issue by kyleabeauchamp** [autoprotocol/autoprotocol-python#27]
So the demo pcr.py (https://www.transcriptic.com/platform/) seems to be written for a previous version of the API, giving the traceback below.  I've also included a diff of the changes necessary to get things running on the latest version.

```
python pcr.py 
Traceback (most recent call last):
  File "pcr.py", line 5, in <module>
    dyes = protocol.ref("dyes", id="ct16ry4kaduqvj", storage="ambient")
  File "/home/kyleb/opt/lib/python2.7/site-packages/autoprotocol-2.0.1-py2.7.egg/autoprotocol/protocol.py", line 218, in ref
    cont_type = self.container_type(cont_type)
  File "/home/kyleb/opt/lib/python2.7/site-packages/autoprotocol-2.0.1-py2.7.egg/autoprotocol/protocol.py", line 142, in container_type
    (shortname, str(_CONTAINER_TYPES.keys())))
ValueError: Unknown container type None (known types=['96-flat', '96-deep', '384-flat', '384-pcr', 'micro-1.5', 'micro-2.0', '96-pcr'])
```

```
diff pcr2.py pcr.py 
5,6c5,6
< dyes = protocol.ref("dyes", id="ct16ry4kaduqvj", cont_type="96-flat", storage="ambient")
< test = protocol.ref("test", id="ct16ry4kagbqqt", cont_type="96-flat", storage="ambient")
---
> dyes = protocol.ref("dyes", id="ct16ry4kaduqvj", storage="ambient")
> test = protocol.ref("test", id="ct16ry4kagbqqt", storage="ambient")
10c10
<     volume="50:microliter")
---
>     vol="50:microliter")
```

**Comment by therzka** [comment]
This is in the process of being changed, thanks for pointing it out!
